CREATE DATABASE rhdemo;
CREATE TABLE rhdemo.testtable (id INT AUTO_INCREMENT PRIMARY KEY, TKTKTK VARCHAR(255) NOT NULL);
INSERT INTO rhdemo.testtable (TKTKTK) VALUES ('tk1'), ('tk2'), ('tk3');
CREATE USER 'flask'@'%' IDENTIFIED BY 'PnWJ9abAq3EAfEeqy7e';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, CREATE TEMPORARY TABLES, CREATE VIEW, EVENT, TRIGGER, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EXECUTE ON `rhdemo`.* TO 'flask'@'%';
