---
- name: ensure /root/app exists
  file:
    path: /root/app
    state: directory

- name: Clone demo repo
  git:
    repo: 'https://github.com/grimsleydl/rhdemo.git'
    dest: /root/app
    clone: yes
    update: yes

- name: ensure /root/unpack exists
  file:
    path: /root/unpack
    state: directory

- name: copy example app to server and extract
  unarchive:
    src: ~/repos/presentations/rhdemo/tmp/rhdemo_py.tar.gz
    dest: /root/unpack
