version: "3"
networks:
  macvlan:
    driver: macvlan
    driver_opts:
      parent: eth1
    ipam:
      config:
        - subnet: "192.168.70.0/24"
          ip_range: "192.168.70.128/27"
          gateway: "192.168.70.1"
          aux_address: "host=192.168.70.129"
