# https://github.com/elastic/ansible-elastic-cloud-enterprise/issues/29 for this
- name: Ensure kernel modules are loaded
  template:
    src: templates/module.conf.j2
    dest: "/etc/modules-load.d/{{ item.name }}.conf"
    mode: 0644
  with_items:
  - { name: 'br_netfilter', kernel_module: 'br_netfilter' }
  - { name: 'overlay', kernel_module: 'overlay' }

- name: Add the br_netfilter module
  modprobe:
    name: br_netfilter
    state: present

- name: Add the overlay module
  modprobe:
    name: overlay
    state: present

- name: Set up routing in sysctl
  sysctl:
    name: "net.ipv4.ip_forward "
    value: "1"
    state: present

- name: Set up bridging in sysctl
  sysctl:
    name: "net.bridge.bridge-nf-call-iptables"
    value: "1"
    state: present

- name: Enable loose reverse path filtering
  sysctl:
    name: "net.ipv4.conf.all.rp_filter"
    value: "2"
    state: present

- name: Set up ip6 bridging in sysctl
  sysctl:
    name: "net.bridge.bridge-nf-call-ip6tables"
    value: "1"
    state: present

- name: set selinux permissive
  selinux:
    policy: targeted
    state: permissive

- name: set up docker repo
  get_url:
    url: "{{ docker_ce_repo }}"
    dest: /etc/yum.repos.d/docer-ce.repo
  become: yes

- name: Install docker
  yum:
    name: "docker-ce"
    state: latest

- name: enable docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: ensure /root dirs exist
  file:
    path: "/root/{{ item }}"
    state: directory
  with_items:
    - bin
    - app
    - docker

- name: install docker compose
  get_url:
    url: "{{ docker_compose_path }}"
    dest: /root/bin/docker-compose
    mode: 0755

- name: enable promiscuous mode on eth1
  command: ip link set dev eth1 promisc on

- name: permanently enable promiscuous mode on eth1
  copy:
    src: ../files/etc/NetworkManager/dispatcher.d/30-promisc
    dest: /etc/NetworkManager/dispatcher.d/30-promisc
    owner: root
    group: root
    mode: 0755

- name: copy dockerfile
  copy:
    src: ../../../../../app/Dockerfile
    dest: /root/app/Dockerfile
    owner: root
    group: root
    mode: 0600

- name: "add templated docker-compose file"
  tags: docker-compose
  template:
    src: docker-compose.yml.j2
    dest: /root/docker/docker-compose.yml
    mode: 0600

- name: copy app directory to container host
  copy:
    src: "../../../../../app/{{ item }}"
    dest: /root/app
  with_items:
    - rhdemo_py
    - poetry.lock
    - pyproject.toml

- name: copy env file to container host
  copy:
    src: "../../../secret/.env"
    dest: /root/docker/.env
    mode: 0600

- name: build container
  command: chdir=/root/docker /root/bin/docker-compose build

- name: launch container
  command: chdir=/root/docker /root/bin/docker-compose up -d
