---
- name: disable firewalld service
  service:
    name: firewalld
    state: stopped
    enabled: no
  tags: setup

- name: Install iptables service
  yum:
    name: iptables-services
    state: latest

- name: enable iptables service
  service:
    name: iptables
    state: started
    enabled: yes
  tags: setup
