---
- name: set the cluster up
  become: true
  import_role:
    name: ondrejhome.ha-cluster-pacemaker
  tags: pcs-setup
  vars:
    cluster_name: db-cluster
    cluster_user_pass: calvincalvin
    cluster_configure_fence_xvm: false
    cluster_configure_fence_kdump: false
    cluster_etc_hosts: false
    cluster_net_iface: 'eth3'
    cluster_fence_config:
      fence_db-1:
        fence_type: 'fence_virsh'
        fence_options: >-
          pcmk_host_map="{% for item in groups['cluster'+rand_id+'_node_is_remote_False'] %}{{ hostvars[item][cluster_hostname_fact] }}:{{ hostvars[item]['vm_name'] }};{% endfor %}" ip=192.168.150.1 username=root identity_file=/root/.ssh/id_ed25519_fence plug=phase1_db-1 ipport=32091 pcmk_host_list=db-2 op monitor interval=30s
      fence_db-2:
        fence_type: 'fence_virsh'
        fence_options: >-
          pcmk_host_map="{% for item in groups['cluster'+rand_id+'_node_is_remote_False'] %}{{ hostvars[item][cluster_hostname_fact] }}:{{ hostvars[item]['vm_name'] }};{% endfor %}" ip=192.168.150.1 username=root identity_file=/root/.ssh/id_ed25519_fence plug=phase1_db-2 ipport=32091 pcmk_host_check=static-list op monitor interval=60s
    cluster_constraint_location:
      - resource: fence_db-1
        node_name: db-2
        score: INFINITY
      - resource: fence_db-2
        node_name: db-1
        score: INFINITY
    cluster_resource:
      - name: dlm
        resource_type: 'ocf:pacemaker:controld'
        options: 'op monitor timeout=60s interval=60s on-fail=standby clone notify=true interleave=true ordered=false'
      - name: lvmlockd
        resource_type: 'ocf:heartbeat:lvmlockd'
        options: 'op monitor timeout=60s interval=60s on-fail=standby clone notify=true interleave=true ordered=false'
      - name: mariadb_lvm
        resource_type: 'ocf:heartbeat:LVM-activate'
        options: 'vgname=vgsan00 vg_access_mode=system_id op monitor interval=10s timeout=10s on-fail=restart'
      - name: mariadb_fs
        resource_type: 'ocf:heartbeat:Filesystem'
        options: 'device="/dev/vgsan00/mysql" directory="/san/mysql-fs" fstype="xfs" op monitor interval=20s timeout=20s on-fail=restart'
      - name: mariadb_ip
        resource_type: 'ocf:heartbeat:IPaddr2'
        options: 'ip=192.168.160.200 cidr_netmask=24 op monitor interval=20s timeout=20s on-fail=restart'
      - name: mariadb_srv
        resource_type: 'ocf:heartbeat:mysql'
        options: 'config="/etc/my.cnf" enable_creation="0" user="mysql" group="mysql" datadir="/san/mysql-fs/mysql" socket="/san/mysql-fs/mysql/mysql.sock" additional_parameters="--bind-address=192.168.160.200" op monitor interval="15s" timeout="15s" on-fail=restart op start interval="0" timeout="300s" op stop interval="0" timeout="300s"'
    cluster_constraint_order:
      - resource1: dlm-clone
        resource1_action: start
        resource2: lvmlockd-clone
        resource2_action: start
