- name: enable lvmlockd
  replace:
    path: /etc/lvm/lvm.conf
    regexp: 'use_lvmlockd = 0'
    replace: 'use_lvmlockd = 1'

- name: set lvm system id source
  replace:
    path: /etc/lvm/lvm.conf
    regexp: 'system_id_source = "none"'
    replace: 'system_id_source = "uname"'

- name: Perform a discovery on 192.168.140.1 and show available target nodes
  open_iscsi:
    show_nodes: yes
    discover: yes
    ip: "{{ iscsi_target }}"
    login: yes

- name: Connect to the target
  open_iscsi:
    login: yes
    target: "{{ target_lun }}"
    auto_node_startup: yes

- name: Fix iscsi on boot
  copy:
    src: "../files/etc/systemd/system/iscsi-boot.service"
    dest: "/etc/systemd/system/iscsi-boot.service"
    mode: 0755

- name: Enable iscsi service on boot
  service:
    name: iscsi-boot
    state: started
    enabled: yes

